# server
spring.application.name=pet_adoption
host.address=http://127.0.0.1:8080
# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
# redis
spring.data.redis.host=
spring.data.redis.database=
# mail
spring.mail.host=
spring.mail.protocol=
spring.mail.port=
spring.mail.username=
spring.mail.password=
# jwt
jwt.secret=
jwt.access-expire-seconds=1800
jwt.refresh-expire-seconds=604800
jwt.header=Authorization
jwt.prefix=Bearer
# file
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
file.upload=./upload_files
file.temp=./temp_files
# timeout
application.key_timeout = 30
application.code_timeout = 10
# redis key
key.token_invalid=pet_adoption.invalid_token.%s
key.password_reset=pet_adoption:user.forgetpwd.%s
key.mail_code=pet_adoption:user.forgetpwd.code.%s
key.agreement.uuid=pet_adoption:agreement.%s
key.agreement.file=pet_adoption:agreement.file.%s
key.rescue_task.uuid=pet_adoption:rescue_task.%s
key.rescue_task.file=pet_adoption:rescue_task.file.%s
key.examination.uuid=pet_adoption:medical.exam.%s
key.examination.file=pet_adoption:medical.exam.file.%s
key.donation.uuid=pet_adoption:donation.%s
key.donation.file=pet_adoption:donation.file.%s
key.lost_pet.uuid=pet_adoption:lost_pet.%s
key.lost_pet.file=pet_adoption:lost_pet.file.%s
