import { createApp } from 'vue'
import { createPinia } from 'pinia'
import './styles/base.css'
import './styles/header-nav.css'
import './styles/home-content.css'
import './styles/auth.css'
import './styles/console.css'
import './styles/detail-pages.css'
import './styles/directory-cards.css'
import './styles/admin-tables.css'
import './styles/article.css'
import './styles/volunteer.css'
import './styles/lost-pet.css'
import './styles/rescue-action.css'
import './styles/pet-profile.css'
import './styles/pet-media.css'
import './styles/image-viewer.css'
import './styles/pet-album.css'
import './styles/media-queries.css'
import ElementPlus from 'element-plus'
import 'element-plus/dist/index.css'
import App from './App.vue'
import router from './router'

createApp(App).use(createPinia()).use(router).use(ElementPlus).mount('#app')

