# server
spring.application.name=pet_adoption
host.address=${HOST}
# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST:127.0.0.1}:3306/pet_adoption?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# redis
spring.data.redis.host=${DB_HOST:127.0.0.1}
spring.data.redis.database=0
# mail
spring.mail.host=${MAIL_HOST}
spring.mail.protocol=${MAIL_PROTOCOL}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_ADDRESS}
spring.mail.password=${MAIL_PASSWORD}
# jwt
jwt.secret=${JWT_SECRET}
jwt.access-expire-seconds=${JWT_EXPIRE_ACCESS}
jwt.refresh-expire-seconds=${JWT_EXPIRE_REFRESH}
jwt.header=Authorization
jwt.prefix=Bearer
# file
spring.servlet.multipart.max-file-size=${FILE_MAX_SIZE}
spring.servlet.multipart.max-request-size=${FILE_MAX_SIZE}
file.upload=${FILE_UPLOAD}
file.temp=${FILE_TEMP}
# timeout
application.key_timeout=30
application.code_timeout=10
application.mail_timeout=30
# redis key
key.token_invalid=pet_adoption.invalid_token.%s
key.password_reset=pet_adoption:user.forgetpwd.%s
key.mail_code=pet_adoption:user.forgetpwd.code.%s
key.mail_code_limit=pet_adoption:user.forgetpwd.code.limit.%s
key.agreement.uuid=pet_adoption:agreement.%s
key.agreement.file=pet_adoption:agreement.file.%s
key.rescue_task.uuid=pet_adoption:rescue_task.%s
key.rescue_task.file=pet_adoption:rescue_task.file.%s
key.examination.uuid=pet_adoption:medical.exam.%s
key.examination.file=pet_adoption:medical.exam.file.%s
key.donation.uuid=pet_adoption:donation.%s
key.donation.file=pet_adoption:donation.file.%s
key.lost_pet.uuid=pet_adoption:lost_pet.%s
key.lost_pet.file=pet_adoption:lost_pet.file.%s
# other
application.admin_user=${ADMIN_USERNAME}
application.admin_password=${ADMIN_PASSWORD}
